version : '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "81:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
  php:
    build: .
    volumes:
      - ./:/code
  database:
    image: mysql:8.2
    environment:
      # 🚨 Changer si vous utilisez cette configuration en production
      MYSQL_ROOT_PASSWORD: CqIEuocUkTClfJyzVfOYcKAzbrHFqH # ⬅︎ 🚨 À changer si production
      MYSQL_DATABASE: injectionDB
      MYSQL_USER: henrique # ⬅︎ 🚨 À changer si production
      MYSQL_PASSWORD: CqIEuocUkTClfJyzVfOYcKAzbrHFqH # ⬅︎ 🚨 À changer si production
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: CqIEuocUkTClfJyzVfOYcKAzbrHFqH # ⬅︎ 🚨 À changer si production
    ports:
      - "82:80"